name: ${COMPOSE_PROJECT_NAME:-apex-stack}

services:
  db:
    image: container-registry.oracle.com/database/free:latest
    container_name: ${COMPOSE_PROJECT_NAME:-apex-stack}-db
    entrypoint: ["/bin/bash", "-c", "/entrypoint.sh"]
    environment:
      ORACLE_CHARACTERSET: ${ORACLE_CHARACTERSET:-AL32UTF8}
      ORACLE_PDB: ${ORACLE_PDB:-FREEPDB1}
      ORACLE_PWD: ${ORACLE_PWD:?Set ORACLE_PWD in .env}
      ENABLE_ARCHIVELOG: ${ENABLE_ARCHIVELOG:-true}
      ENABLE_FORCE_LOGGING: ${ENABLE_FORCE_LOGGING:-true}
      APEX_PUBLIC_USER_PWD: ${APEX_PUBLIC_USER_PWD:?Set APEX_PUBLIC_USER_PWD in .env}
      APEX_LISTENER_PWD: ${APEX_LISTENER_PWD:?Set APEX_LISTENER_PWD in .env}
      APEX_REST_PUBLIC_USER_PWD: ${APEX_REST_PUBLIC_USER_PWD:?Set APEX_REST_PUBLIC_USER_PWD in .env}
      APEX_ADMIN_PWD: ${APEX_ADMIN_PWD:?Set APEX_ADMIN_PWD in .env}
      APEX_TABLESPACE_NAME: ${APEX_TABLESPACE_NAME:-APEX}
      APEX_TABLESPACE_FILE_NAME: ${APEX_TABLESPACE_FILE_NAME:-apex_001.dbf}
    ports:
      - "${HOST_DB_PORT:-1521}:1521"
    volumes:
      - ./container-data/db/jdk:/jdk:U,ro # fetch with scripts/prepare-java.sh
      - ./container-data/db/sqlcl:/sqlcl:U,ro # fetch with scripts/prepare-sqlcl.sh
      - ./container-data/db/apex:/apex:U,ro # fetch with scripts/prepare-apex.sh
      - ./container-data/db/oradata:/opt/oracle/oradata:U # persistent database storage
      - ./container-scripts/db/entrypoint.sh:/entrypoint.sh:U,ro # Custom entrypoint
      - ./container-scripts/db/setup:/opt/oracle/scripts/setup:U,ro # Setup scripts
      - ./container-scripts/db/startup:/opt/oracle/scripts/startup:U,ro # Startup scripts
      - ./container-data/db/apex-install:/apex-install:U # APEX installation log files

  # ords:
  #   image: container-registry.oracle.com/database/ords:latest
  #   container_name: ${COMPOSE_PROJECT_NAME:-apex-stack}-ords
  #   entrypoint: ["/ords-local-entrypoint.sh"]
  #   depends_on:
  #     - db
  #   environment:
  #     DBHOST: db
  #     DBPORT: 1521
  #     DBSERVICENAME: FREEPDB1
  #     DB_WAIT_RETRY: 90
  #     APEX_INSTALL_WAIT_SECONDS: 3600
  #     ORACLE_PWD: ${ORACLE_PWD:?Set ORACLE_PWD in .env}
  #     ORACLE_USER_PWD: ${ORDS_PUBLIC_USER_PWD:?Set ORDS_PUBLIC_USER_PWD in .env}
  #     APEX_ADMIN_PWD: ${APEX_ADMIN_PWD:?Set APEX_ADMIN_PWD in .env}
  #   ports:
  #     - "${HOST_ORDS_PORT:-8181}:8080"
  #   volumes:
  #     - ./apex:/opt/oracle/apex:ro
  #     - ./ords_config:/etc/ords/config
  #     # - ./data/oradata:/opt/oracle/oradata:ro
  #     - ./scripts/ords-local-entrypoint.sh:/ords-local-entrypoint.sh:ro
  #     - ./scripts/ords-entrypoint.d:/ords-entrypoint.d:ro
